Upgrade rake (#80)
The release failed with the following error due to an old version of
rake:

```
NoMethodError: undefined method `=~' for an instance of Proc
/home/jenkins/.rbenv/versions/3.3.10/bin/bundle:25:in `load'
/home/jenkins/.rbenv/versions/3.3.10/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)
```

Upgrading to a more modern version of Rake fixes the problem.